version: '3.7'

services:
  myapitemplate:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: callysta-template
    restart: always
    env_file:
      - .env
    volumes:
      - "./app:/app"
    ports:
      - "80:80"